from aiogram.dispatcher.filters.state import StatesGroup, State


class Data_collector_states(StatesGroup):
    waiting_for_customer_number = State()
    customer_number_input = State()
    manager_waiting = State()
    manager_add_employee = State()
    manager_add_username_employee = State()
    manager_delete_employee = State()
    manager_customer_number_input = State()
    admin_waiting = State()
    admin_store = State()
    admin_add_store_city = State()
    admin_add_store_name = State()
    admin_delete_store_city = State()
    admin_delete_store_name = State()
    admin_manager = State()
    admin_add_manager_city = State()
    admin_add_manager_store = State()
    admin_add_manager_name = State()
    admin_add_manager_username = State()
    admin_delete_manager_city = State()
    admin_delete_manager_store = State()
    admin_delete_manager_name = State()
    admin_worker = State()
    admin_add_worker_city = State()
    admin_add_worker_store = State()
    admin_add_worker_name = State()
    admin_add_worker_username = State()
    admin_delete_worker_city = State()
    admin_delete_worker_store = State()
    admin_delete_worker_name = State()
    super_admin = State()
    super_admin_add_admin = State()
    super_admin_delete_admin = State()
    finish = State()
